name: climatic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  toastification: ^3.0.2
  fluttertoast: ^8.2.12
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  bcrypt: ^1.1.3
  shared_preferences: ^2.5.3
  firebase_database: ^11.3.5
  fl_chart: ^0.70.2
  intl: ^0.20.2
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/dark_theme.jpg
  - assets/images/light_theme.png
